/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: 'var(--color-primary)',
        'primary-hover': 'var(--color-primary-hover)',
        accent: 'var(--color-accent)',
        background: 'var(--color-background)',
        surface: 'var(--color-surface)',
        'surface-hover': 'var(--color-surface-hover)',
        elevated: 'var(--color-elevated)',
        foreground: 'var(--color-foreground)',
        muted: 'var(--color-muted)',
        border: 'var(--color-border)',
        destructive: 'var(--color-destructive)',
        ring: 'var(--color-ring)',
        favorite: 'var(--color-favorite)',
        success: 'var(--color-success)',
        'badge-file': 'var(--color-badge-file)',
        'badge-file-bg': 'var(--color-badge-file-bg)',
        'image-bg': 'var(--color-image-bg)',
        titlebar: 'var(--color-titlebar)',
        separator: 'var(--color-separator)',
        'primary-alpha-04': 'var(--color-primary-alpha-04)',
        'primary-alpha-06': 'var(--color-primary-alpha-06)',
        'primary-alpha-08': 'var(--color-primary-alpha-08)',
        'primary-alpha-12': 'var(--color-primary-alpha-12)',
        'primary-alpha-15': 'var(--color-primary-alpha-15)',
        'glass-bg': 'var(--toast-glass-bg)',
        'glass-border': 'var(--glass-border)',
      },
      borderRadius: {
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        full: 'var(--radius-full)',
      },
      fontSize: {
        xs: 'var(--font-size-xs)',
        sm: 'var(--font-size-sm)',
        base: 'var(--font-size-base)',
        lg: 'var(--font-size-lg)',
        xl: 'var(--font-size-xl)',
        '2xl': 'var(--font-size-2xl)',
      },
      spacing: {
        '1': 'var(--space-1)',
        '2': 'var(--space-2)',
        '3': 'var(--space-3)',
        '4': 'var(--space-4)',
        '6': 'var(--space-6)',
        '8': 'var(--space-8)',
      },
      transitionDuration: {
        fast: 'var(--transition-fast)',
        normal: 'var(--transition-normal)',
      },
      boxShadow: {
        'glass': 'var(--shadow-glass)',
        'glass-lg': 'var(--shadow-glass-lg)',
        'card': 'var(--shadow-card)',
        'popup': 'var(--shadow-popup)',
      },
      backdropBlur: {
        glass: 'var(--blur-glass)',
      },
    },
  },
  plugins: [],
}
