// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Stats holds aggregate clipboard statistics.
 */
export class Stats {
    /**
     * Creates a new Stats instance.
     * @param {Partial<Stats>} [$$source = {}] - The source object to create the Stats.
     */
    constructor($$source = {}) {
        if (!("count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["count"] = 0;
        }
        if (!("total_bytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total_bytes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Stats instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Stats}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Stats(/** @type {Partial<Stats>} */($$parsedSource));
    }
}

/**
 * SyncFormat is a text format payload for sync push.
 */
export class SyncFormat {
    /**
     * Creates a new SyncFormat instance.
     * @param {Partial<SyncFormat>} [$$source = {}] - The source object to create the SyncFormat.
     */
    constructor($$source = {}) {
        if (!("t" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["t"] = 0;
        }
        if (!("c" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["c"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SyncFormat instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SyncFormat}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SyncFormat(/** @type {Partial<SyncFormat>} */($$parsedSource));
    }
}
