// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service provides clipboard history queries and actions.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as clipboard$0 from "../clipboard/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CaptureEntry persists or deduplicates a clipboard entry.
 * @param {clipboard$0.CapturedData} data
 * @returns {$CancellablePromise<[clipboard$0.Entry | null, boolean]>}
 */
export function CaptureEntry(data) {
    return $Call.ByID(3907808002, data).then(/** @type {($result: any) => any} */(($result) => {
        $result[0] = $$createType1($result[0]);
        return $result;
    }));
}

/**
 * Cleanup removes entries older than retainDays and their image files.
 * @param {number} retainDays
 * @returns {$CancellablePromise<number>}
 */
export function Cleanup(retainDays) {
    return $Call.ByID(4117285412, retainDays);
}

/**
 * ClearAll deletes all clipboard entries and their image files.
 * @returns {$CancellablePromise<void>}
 */
export function ClearAll() {
    return $Call.ByID(706678788);
}

/**
 * DeleteEntry removes a single entry by ID.
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteEntry(id) {
    return $Call.ByID(3832500157, id);
}

/**
 * GetHistory returns entries with cursor-based pagination and tag filtering.
 * tagMask=0 means all, afterUpdatedAt="" means first page.
 * @param {string} search
 * @param {number} tagMask
 * @param {string} afterUpdatedAt
 * @param {number} afterID
 * @returns {$CancellablePromise<[clipboard$0.Entry[], boolean]>}
 */
export function GetHistory(search, tagMask, afterUpdatedAt, afterID) {
    return $Call.ByID(2097755524, search, tagMask, afterUpdatedAt, afterID).then(/** @type {($result: any) => any} */(($result) => {
        $result[0] = $$createType2($result[0]);
        return $result;
    }));
}

/**
 * GetImageDataURL returns a base64 data URL for the first image format of an entry.
 * @param {number} entryID
 * @returns {$CancellablePromise<string>}
 */
export function GetImageDataURL(entryID) {
    return $Call.ByID(2477571378, entryID);
}

/**
 * GetStats returns count and total content size.
 * @returns {$CancellablePromise<$models.Stats>}
 */
export function GetStats() {
    return $Call.ByID(875684879).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * UseEntry performs the default action and refreshes updated_at.
 * @param {number} id
 * @param {string} action
 * @returns {$CancellablePromise<void>}
 */
export function UseEntry(id, action) {
    return $Call.ByID(3620211189, id, action);
}

// Private type creation functions
const $$createType0 = clipboard$0.Entry.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType0);
const $$createType3 = $models.Stats.createFrom;
