// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service provides clipboard history queries and actions.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as clipboard$0 from "../clipboard/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CaptureEntry persists or deduplicates a clipboard entry.
 * Returns the new entry (if inserted) and whether a new row was created.
 * @param {string} text
 * @param {string} hash
 * @returns {$CancellablePromise<[clipboard$0.Entry | null, boolean]>}
 */
export function CaptureEntry(text, hash) {
    return $Call.ByID(3907808002, text, hash).then(/** @type {($result: any) => any} */(($result) => {
        $result[0] = $$createType1($result[0]);
        return $result;
    }));
}

/**
 * Cleanup removes entries older than the specified number of days.
 * @param {number} retainDays
 * @returns {$CancellablePromise<number>}
 */
export function Cleanup(retainDays) {
    return $Call.ByID(4117285412, retainDays);
}

/**
 * DeleteEntry removes a single entry by ID.
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteEntry(id) {
    return $Call.ByID(3832500157, id);
}

/**
 * GetHistory returns clipboard entries matching the optional search string,
 * ordered by updated_at descending. Limit 200.
 * @param {string} search
 * @returns {$CancellablePromise<clipboard$0.Entry[]>}
 */
export function GetHistory(search) {
    return $Call.ByID(2097755524, search).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetStats returns count and total content size.
 * @returns {$CancellablePromise<$models.Stats>}
 */
export function GetStats() {
    return $Call.ByID(875684879).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * UseEntry performs the default action (copy or paste) and refreshes updated_at.
 * @param {number} id
 * @param {string} action
 * @returns {$CancellablePromise<void>}
 */
export function UseEntry(id, action) {
    return $Call.ByID(3620211189, id, action);
}

// Private type creation functions
const $$createType0 = clipboard$0.Entry.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType0);
const $$createType3 = $models.Stats.createFrom;
