// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../encoding/json/models.js";

/**
 * Data holds user-configurable settings.
 */
export class Data {
    /**
     * Creates a new Data instance.
     * @param {Partial<Data>} [$$source = {}] - The source object to create the Data.
     */
    constructor($$source = {}) {
        if (!("hotkey" in $$source)) {
            /**
             * "Alt+V"
             * @member
             * @type {string}
             */
            this["hotkey"] = "";
        }
        if (!("retain_days" in $$source)) {
            /**
             * 30
             * @member
             * @type {number}
             */
            this["retain_days"] = 0;
        }
        if (!("default_action" in $$source)) {
            /**
             * "copy" or "paste"
             * @member
             * @type {string}
             */
            this["default_action"] = "";
        }
        if (!("auto_start" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["auto_start"] = false;
        }
        if (!("start_minimized" in $$source)) {
            /**
             * start minimized to tray
             * @member
             * @type {boolean}
             */
            this["start_minimized"] = false;
        }
        if (!("notify_enabled" in $$source)) {
            /**
             * show toast on new clipboard
             * @member
             * @type {boolean}
             */
            this["notify_enabled"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * frontend-managed, Go pass-through
             * @member
             * @type {json$0.RawMessage | undefined}
             */
            this["action_config"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Data instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Data}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Data(/** @type {Partial<Data>} */($$parsedSource));
    }
}
