// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service reads and writes settings from a JSON file.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetSettings returns the current settings for the frontend.
 * @returns {$CancellablePromise<$models.Data>}
 */
export function GetSettings() {
    return $Call.ByID(2816427610).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Load reads settings from disk, falling back to defaults on error.
 * @returns {$CancellablePromise<void>}
 */
export function Load() {
    return $Call.ByID(2167222137);
}

/**
 * OnHotkeyChange sets a callback invoked when the hotkey setting changes.
 * @param {any} fn
 * @returns {$CancellablePromise<void>}
 */
export function OnHotkeyChange(fn) {
    return $Call.ByID(51238398, fn);
}

/**
 * OnSettingsChange sets a callback invoked when any non-hotkey setting changes.
 * @param {any} fn
 * @returns {$CancellablePromise<void>}
 */
export function OnSettingsChange(fn) {
    return $Call.ByID(2105361349, fn);
}

/**
 * Save writes settings to disk.
 * @returns {$CancellablePromise<void>}
 */
export function Save() {
    return $Call.ByID(3509559832);
}

/**
 * SaveSettings updates and persists settings.
 * @param {$models.Data} d
 * @returns {$CancellablePromise<void>}
 */
export function SaveSettings(d) {
    return $Call.ByID(3104659525, d);
}

// Private type creation functions
const $$createType0 = $models.Data.createFrom;
