import { useState, useEffect, useRef } from 'react'
import { useSearchParams } from 'react-router-dom'
import { Window } from '@wailsio/runtime'
import JSONEditor from 'jsoneditor'
import 'jsoneditor/dist/jsoneditor.css'

// Wails auto-generated binding — generated by `wails3 dev` / `wails3 build`.
// eslint-disable-next-line import/no-unresolved
import { Service as HistoryService } from '../../bindings/jpaste/internal/history'

export default function JsonViewPage() {
  const [searchParams] = useSearchParams()
  const entryId = parseInt(searchParams.get('id'), 10)
  const [jsonData, setJsonData] = useState(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState(null)
  const containerRef = useRef(null)
  const editorRef = useRef(null)
  const fetchedRef = useRef(false)

  console.log('[JsonViewPage] render, id=', entryId, 'loading=', loading, 'hasData=', !!jsonData)

  // Fetch JSON content by entry ID from the database.
  useEffect(() => {
    if (!entryId) {
      setLoading(false)
      setError('缺少 entry ID 参数')
      return
    }
    if (fetchedRef.current) {
      console.log('[JsonViewPage] skip duplicate fetch (StrictMode)')
      return
    }
    fetchedRef.current = true

    console.log('[JsonViewPage] calling GetEntryContent, id=', entryId)
    HistoryService.GetEntryContent(entryId)
      .then((data) => {
        console.log('[JsonViewPage] data received, len=', data?.length)
        if (!data) {
          setError('条目内容为空')
          setLoading(false)
        } else {
          try {
            setJsonData(JSON.parse(data))
          } catch (e) {
            setError('JSON 解析失败: ' + e.message)
          }
          setLoading(false)
        }
      })
      .catch((err) => {
        console.error('[JsonViewPage] fetch error:', err)
        setError(err?.message || '获取数据失败')
        setLoading(false)
      })
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [entryId])

  // Create editor AFTER the container div is mounted and jsonData is ready.
  useEffect(() => {
    if (!jsonData || !containerRef.current) {
      console.log('[JsonViewPage] editor init skipped, container=', !!containerRef.current, 'data=', !!jsonData)
      return
    }
    if (editorRef.current) {
      console.log('[JsonViewPage] editor already exists, updating data')
      editorRef.current.update(jsonData)
      return
    }

    console.log('[JsonViewPage] creating JSONEditor instance')
    const editor = new JSONEditor(containerRef.current, {
      mode: 'tree',
      modes: ['tree', 'code'],
      mainMenuBar: true,
      navigationBar: true,
      statusBar: true,
      search: true,
      history: true,
      indentation: 2,
      sortObjectKeys: false,
      limitDragging: false,
    }, jsonData)

    editorRef.current = editor
    console.log('[JsonViewPage] editor created OK')
  }, [jsonData])

  // Cleanup on unmount.
  useEffect(() => {
    return () => {
      if (editorRef.current) {
        console.log('[JsonViewPage] destroying editor')
        editorRef.current.destroy()
        editorRef.current = null
      }
    }
  }, [])

  // Esc closes the JSON viewer window.
  useEffect(() => {
    const handler = (e) => {
      if (e.key !== 'Escape') return
      const tag = document.activeElement?.tagName
      if (tag === 'INPUT' || tag === 'TEXTAREA' || document.activeElement?.isContentEditable) return
      e.preventDefault()
      Window.Hide()
    }
    document.addEventListener('keydown', handler)
    return () => document.removeEventListener('keydown', handler)
  }, [])

  return (
    <div style={{ width: '100%', height: '100vh', position: 'relative' }}>
      <div ref={containerRef} style={styles.container} />

      {loading && (
        <div style={styles.overlay}>
          <span style={styles.text}>加载中...</span>
        </div>
      )}

      {error && !loading && (
        <div style={styles.overlay}>
          <div>
            <span style={{ ...styles.text, color: 'var(--color-destructive, #EF4444)' }}>
              错误: {error}
            </span>
            <br />
            <span style={{ ...styles.text, fontSize: '12px', marginTop: '8px' }}>
              Entry ID: {entryId || '(无)'}
            </span>
          </div>
        </div>
      )}
    </div>
  )
}

const styles = {
  container: {
    width: '100%',
    height: '100vh',
  },
  overlay: {
    position: 'absolute',
    inset: 0,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: '#F8FAFC',
    flexDirection: 'column',
    zIndex: 1,
  },
  text: {
    fontSize: '14px',
    color: 'var(--color-muted, #94A3B8)',
    fontFamily: 'Inter, system-ui, sans-serif',
  },
}
