import { useState, useEffect } from 'react'
import { useSearchParams } from 'react-router-dom'

// Wails auto-generated binding — generated by `wails3 dev` / `wails3 build`.
// eslint-disable-next-line import/no-unresolved
import { Service as ToastService } from '../../bindings/jpaste/internal/toast'

export default function ToastPage() {
  const [searchParams] = useSearchParams()
  const token = searchParams.get('token')
  const [title, setTitle] = useState('')
  const [message, setMessage] = useState('')
  const [phase, setPhase] = useState('enter') // enter → stay → exit
  const [ready, setReady] = useState(false)

  useEffect(() => {
    if (!token) return
    ToastService.GetToastData(token).then((data) => {
      if (data) {
        setTitle(data.title || 'jPaste')
        setMessage(data.message || '')
      }
      setReady(true)
    }).catch(() => {
      setReady(true)
    })
  }, [token])

  // Animation timeline: 200ms enter → 2600ms stay → 150ms exit
  // Window close is handled by Go side after 3s.
  useEffect(() => {
    if (!ready) return
    const t1 = setTimeout(() => setPhase('stay'), 200)
    const t2 = setTimeout(() => setPhase('exit'), 200 + 2600)
    return () => { clearTimeout(t1); clearTimeout(t2) }
  }, [ready])

  const opacity = phase === 'enter' ? 0 : phase === 'exit' ? 0 : 1
  const transition = phase === 'enter' || phase === 'exit'
    ? 'opacity 150ms ease-in'
    : 'opacity 200ms ease-out'

  return (
    <div style={{
      width: '100%', height: '100vh',
      display: 'flex', alignItems: 'center',
      fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
      opacity, transition,
      userSelect: 'none', cursor: 'default',
    }}>
      <div style={{
        display: 'flex', alignItems: 'center', gap: '10px',
        padding: '0 16px', width: '100%',
      }}>
        <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="#555" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
          <rect x="8" y="2" width="8" height="4" rx="1" ry="1" />
          <path d="M16 4h2a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h2" />
          <path d="M12 11h4" /><path d="M12 16h4" /><path d="M8 11h.01" /><path d="M8 16h.01" />
        </svg>
        <div style={{ flex: 1, overflow: 'hidden' }}>
          <div style={{
            fontSize: '13px', fontWeight: 600, color: '#333',
            whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis',
          }}>{title}</div>
          <div style={{
            fontSize: '12px', color: '#666',
            whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis',
            marginTop: '2px',
          }}>{message}</div>
        </div>
      </div>
    </div>
  )
}
