// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as history$0 from "../history/models.js";

/**
 * Config holds WebDAV connection credentials.
 * Stored in %APPDATA%/jPaste/webdav.json — not synced.
 */
export class Config {
    /**
     * Creates a new Config instance.
     * @param {Partial<Config>} [$$source = {}] - The source object to create the Config.
     */
    constructor($$source = {}) {
        if (!("url" in $$source)) {
            /**
             * e.g. "https://dav.jianguoyun.com/dav/"
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("username" in $$source)) {
            /**
             * 坚果云 account
             * @member
             * @type {string}
             */
            this["username"] = "";
        }
        if (!("password" in $$source)) {
            /**
             * 坚果云 app password (not login password)
             * @member
             * @type {string}
             */
            this["password"] = "";
        }
        if (!("enabled" in $$source)) {
            /**
             * user-toggleable enable/disable
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Config}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Config(/** @type {Partial<Config>} */($$parsedSource));
    }
}

/**
 * PushInput is a clipboard entry queued for upload.
 */
export class PushInput {
    /**
     * Creates a new PushInput instance.
     * @param {Partial<PushInput>} [$$source = {}] - The source object to create the PushInput.
     */
    constructor($$source = {}) {
        if (!("ContentHash" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ContentHash"] = "";
        }
        if (!("Formats" in $$source)) {
            /**
             * @member
             * @type {history$0.SyncFormat[]}
             */
            this["Formats"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PushInput instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PushInput}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Formats" in $$parsedSource) {
            $$parsedSource["Formats"] = $$createField1_0($$parsedSource["Formats"]);
        }
        return new PushInput(/** @type {Partial<PushInput>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = history$0.SyncFormat.createFrom;
const $$createType1 = $Create.Array($$createType0);
