// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service drives the WebDAV bidirectional sync loop.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<$models.Config>}
 */
export function GetConfig() {
    return $Call.ByID(2594562159).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function PullSettings() {
    return $Call.ByID(3068248097).then(/** @type {($result: any) => any} */(($result) => {
        return $Create.ByteSlice($result);
    }));
}

/**
 * @param {$models.PushInput} input
 * @returns {$CancellablePromise<void>}
 */
export function PushEntry(input) {
    return $Call.ByID(632318497, input);
}

/**
 * @param {string} data
 * @returns {$CancellablePromise<void>}
 */
export function PushSettings(data) {
    return $Call.ByID(683392698, data);
}

/**
 * @param {$models.Config} c
 * @returns {$CancellablePromise<void>}
 */
export function SaveConfig(c) {
    return $Call.ByID(3455518264, c);
}

/**
 * @param {$models.Config} c
 * @returns {$CancellablePromise<void>}
 */
export function TestConnection(c) {
    return $Call.ByID(3235294559, c);
}

// Private type creation functions
const $$createType0 = $models.Config.createFrom;
