// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service handles opening clipboard entries in external applications.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * OpenFileLocation opens the folder containing the file path and selects the file.
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function OpenFileLocation(id) {
    return $Call.ByID(1444465364, id);
}

/**
 * OpenInEditor creates a temp .txt file and opens it in the preferred editor.
 * Tries VS Code first, then falls back to the system default .txt handler.
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function OpenInEditor(id) {
    return $Call.ByID(1350443999, id);
}

/**
 * OpenInExplorer opens the folder path contained in a clipboard entry in Windows Explorer.
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function OpenInExplorer(id) {
    return $Call.ByID(21819145, id);
}
