// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service handles opening clipboard entries in external applications.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * OpenInEditor writes the entry's text content to a temp file and opens it
 * in VS Code (if available) or the system default .txt handler.
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function OpenInEditor(id) {
    return $Call.ByID(1350443999, id);
}

/**
 * OpenInExplorer opens the folder containing the entry in Explorer.
 * If the entry content is a valid path format, it opens that path directly.
 * @param {number} id
 * @param {boolean} selectFile
 * @returns {$CancellablePromise<void>}
 */
export function OpenInExplorer(id, selectFile) {
    return $Call.ByID(21819145, id, selectFile);
}
